#Generated by Fabric Compiler ( version 2020.1-SP4 <build 56547> ) at Thu Dec 10 21:18:52 2020

project -load "F:/mdio_1210/synthesize/synplify_impl/../synplify_pro.prj"
open_file "F:/mdio_1210/synthesize/synplify_impl/synplify.srs"
